+ source ../common/disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n function ']'
+ config_params
+ LOG_INFO 'Start to config params of the case.'
+ message='Start to config params of the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to config params of the case.'
Thu Jul 27 23:15:55 2023 - INFO  - Start to config params of the case.
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/get_test_device.py", line 127, in <module>
    print(get_test_disk(args.node))
  File "/root/mugen/libs/locallibs/get_test_device.py", line 98, in get_test_disk
    conn = ssh_cmd.pssh_conn(
  File "/root/mugen/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 349, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python3.10/site-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 349, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
TimeoutError: [Errno 110] Connection timed out
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
++ awk -F '[' '{print$2}' /sys/block//queue/scheduler
++ awk -F ']' '{print$1}'
awk: fatal: cannot open file `/sys/block//queue/scheduler' for reading: No such file or directory
+ old_scheduler=
+ echo bfq
oe_test_disk_schedule_specific.sh: line 23: /sys/block//queue/scheduler: No such file or directory
+ LOG_INFO 'End to config params of the case.'
+ message='End to config params of the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to config params of the case.'
Thu Jul 27 23:18:13 2023 - INFO  - End to config params of the case.
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Jul 27 23:18:14 2023 - INFO  - Start to run test.
+ awk -F ']' '{print$1}'
+ awk -F '[' '{print$2}' /sys/block//queue/scheduler
+ grep bfq
awk: fatal: cannot open file `/sys/block//queue/scheduler' for reading: No such file or directory
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_disk_schedule_specific.sh line 30'
+ message='oe_test_disk_schedule_specific.sh line 30'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_disk_schedule_specific.sh line 30'
Thu Jul 27 23:18:16 2023 - ERROR - oe_test_disk_schedule_specific.sh line 30
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Jul 27 23:18:17 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 1
+ test 1 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Jul 27 23:18:18 2023 - ERROR - failed to execute the case.
+ exit 1
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Jul 27 23:18:19 2023 - INFO  - Start to restore the test environment.
+ echo ''
oe_test_disk_schedule_specific.sh: line 36: /sys/block//queue/scheduler: No such file or directory
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Jul 27 23:18:21 2023 - INFO  - End to restore the test environment.
