+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Fri Jul 28 01:45:28 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'zlib zlib-devel gcc'
+ pkgs='zlib zlib-devel gcc'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'zlib zlib-devel gcc' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmphhxkwqsc
+ '[' -z '' ']'
+ tmpfile=/tmp/tmphhxkwqsc
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Fri Jul 28 01:46:36 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Jul 28 01:46:37 2023 - INFO  - Start to run test.
+ gcc -Wall -o test test.c -lz
In file included from /usr/include/bits/posix1_lim.h:161,
                 from /usr/include/limits.h:195,
                 from /usr/lib/gcc/riscv64-linux-gnu/10.3.1/include/limits.h:195,
                 from /usr/lib/gcc/riscv64-linux-gnu/10.3.1/include/syslimits.h:7,
                 from /usr/lib/gcc/riscv64-linux-gnu/10.3.1/include/limits.h:34,
                 from /usr/include/zconf.h:424,
                 from /usr/include/zlib.h:34,
                 from test.c:2:
/usr/include/bits/local_lim.h:38:10: fatal error: linux/limits.h: No such file or directory
   38 | #include <linux/limits.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
+ CHECK_RESULT 1 0 0 'compile file error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='compile file error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'compile file error'
+ LOG_ERROR 'compile file error'
+ message='compile file error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'compile file error'
Fri Jul 28 01:46:40 2023 - ERROR - compile file error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_zlib.sh line 30'
+ message='oe_test_zlib.sh line 30'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_zlib.sh line 30'
Fri Jul 28 01:46:41 2023 - ERROR - oe_test_zlib.sh line 30
+ '[' 0 -eq 1 ']'
+ return 0
+ ./test
oe_test_zlib.sh: line 31: ./test: No such file or directory
+ grep -E 'Src string:hello world! aaaaa bbbbb ccccc ddddd|UnCompressed String:hello world! aaaaa bbbbb ccccc ddddd'
+ CHECK_RESULT 1 0 0 'grep msg error'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep msg error'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep msg error'
+ LOG_ERROR 'grep msg error'
+ message='grep msg error'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'grep msg error'
Fri Jul 28 01:46:42 2023 - ERROR - grep msg error
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_zlib.sh line 32'
+ message='oe_test_zlib.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_zlib.sh line 32'
Fri Jul 28 01:46:44 2023 - ERROR - oe_test_zlib.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Jul 28 01:46:45 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Jul 28 01:46:46 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Fri Jul 28 01:46:48 2023 - INFO  - start environment cleanup.
+ rm -rf test
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmphhxkwqsc ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmphhxkwqsc
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Fri Jul 28 01:47:07 2023 - INFO  - Finish environment cleanup!
