+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Jul 27 19:00:11 2023 - INFO  - Start to prepare the test environment.
+ OLD_LANG=en_US.UTF-8
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ DNF_INSTALL fuse
+ pkgs=fuse
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs fuse --node 1 --tempfile ''
Thu Jul 27 19:00:29 2023 - INFO  - pkgs:(fuse) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Thu Jul 27 19:00:31 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Thu Jul 27 19:00:32 2023 - INFO  - Start testing...
+ mkdir /home/test
+ test -d /home/test
+ CHECK_RESULT 0 0 0 'The test is not exit '
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The test is not exit '
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mount -t fusectl none /home/test
mount: /home/test: unknown filesystem type 'fusectl'.
+ CHECK_RESULT 32 0 0 'The fuse test is fail'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='The fuse test is fail'
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'The fuse test is fail'
+ LOG_ERROR 'The fuse test is fail'
+ message='The fuse test is fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The fuse test is fail'
Thu Jul 27 19:00:34 2023 - ERROR - The fuse test is fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fuse.sh line 36'
+ message='oe_test_fuse.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fuse.sh line 36'
Thu Jul 27 19:00:35 2023 - ERROR - oe_test_fuse.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ mount
+ grep fusectl
+ CHECK_RESULT 1 0 0 'The relust is abnormal'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The relust is abnormal'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The relust is abnormal'
+ LOG_ERROR 'The relust is abnormal'
+ message='The relust is abnormal'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The relust is abnormal'
Thu Jul 27 19:00:37 2023 - ERROR - The relust is abnormal
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fuse.sh line 38'
+ message='oe_test_fuse.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fuse.sh line 38'
Thu Jul 27 19:00:38 2023 - ERROR - oe_test_fuse.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /home/test
umount: /home/test: not mounted.
+ CHECK_RESULT 32 0 0 'The umount test is fail'
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log='The umount test is fail'
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n 'The umount test is fail'
+ LOG_ERROR 'The umount test is fail'
+ message='The umount test is fail'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The umount test is fail'
Thu Jul 27 19:00:39 2023 - ERROR - The umount test is fail
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fuse.sh line 40'
+ message='oe_test_fuse.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fuse.sh line 40'
Thu Jul 27 19:00:40 2023 - ERROR - oe_test_fuse.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Thu Jul 27 19:00:42 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Jul 27 19:00:43 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Jul 27 19:00:44 2023 - INFO  - Start to restore the test environment.
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Jul 27 19:00:46 2023 - WARN  - no thing to do.
+ return 0
+ rm -rf /home/test
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Jul 27 19:00:47 2023 - INFO  - End to restore the test environment.
